export const UPDATE_RESPONSE_DATA = 'UPDATE_RESPONSE_DATA';
export const CREATE_PRODUCT_LIST = 'CREATE_PRODUCT_LIST';
export const ADD_PRODUCT_TO_COMPARE = 'ADD_PRODUCT_TO_COMPARE';
export const REMOVE_PRODUCT_FROM_COMPARE = 'REMOVE_PRODUCT_FROM_COMPARE';
export const TOGGLE_SHOW_DIFFERENT = 'TOGGLE_SHOW_DIFFERENT';
export const UPDATE_API_ERROR = 'API_ERROR';
export const SHOW_LOADER = 'SHOW_LOADER';

const ACTION_TYPES = {
    UPDATE_RESPONSE_DATA,
    CREATE_PRODUCT_LIST,
    ADD_PRODUCT_TO_COMPARE,
    REMOVE_PRODUCT_FROM_COMPARE,
    TOGGLE_SHOW_DIFFERENT,
    UPDATE_API_ERROR,
    SHOW_LOADER,
};

export default ACTION_TYPES;
